"""LogSeal — Audit logging for B2B SaaS."""

from logseal.client import LogSeal
from logseal.errors import LogSealError
from logseal.types import (
    Actor,
    ActorInput,
    AuditEvent,
    BatchEmitResponse,
    CreateExportInput,
    CreateOrganizationInput,
    CreateSchemaInput,
    CreateViewerTokenInput,
    CreateWebhookInput,
    EmitEventInput,
    EmitEventResponse,
    EventContext,
    EventSchema,
    Export,
    ExportFilters,
    ListEventsParams,
    MerkleProofResponse,
    Organization,
    PaginatedList,
    Target,
    TargetInput,
    UpdateSchemaInput,
    UpdateWebhookInput,
    VerifyParams,
    VerifyRangeParams,
    VerifyRangeResponse,
    VerifyResponse,
    ViewerToken,
    Webhook,
    WebhookWithSecret,
)

__all__ = [
    "LogSeal",
    "LogSealError",
    "Actor",
    "ActorInput",
    "AuditEvent",
    "BatchEmitResponse",
    "CreateExportInput",
    "CreateOrganizationInput",
    "CreateSchemaInput",
    "CreateViewerTokenInput",
    "CreateWebhookInput",
    "EmitEventInput",
    "EmitEventResponse",
    "EventContext",
    "EventSchema",
    "Export",
    "ExportFilters",
    "ListEventsParams",
    "MerkleProofResponse",
    "Organization",
    "PaginatedList",
    "Target",
    "TargetInput",
    "UpdateSchemaInput",
    "UpdateWebhookInput",
    "VerifyParams",
    "VerifyRangeParams",
    "VerifyRangeResponse",
    "VerifyResponse",
    "ViewerToken",
    "Webhook",
    "WebhookWithSecret",
]

__version__ = "0.1.0"
